// src/utils/localization.js

export const LOCALIZATION = {
  zh: { // 简体中文
    ui: {
      title: "1989 · 铁幕镜头",
      subtitle: "The Lens of History",
      intro_1: "【历史前夜】1989年6月，北京。长夜如墨，戒严的阴影笼罩街头。作为一名孤身前往现场的香港纪实记者，你正站在历史的十字路口。四周是绝对不透光的砖石围墙，墙角后全是不见底的盲区，危险随时可能从阴暗处暴起。你唯一的武器，是胸前挂着的一台老旧胶片相机，以及暗盒里仅剩的 5 张胶卷。",
      intro_2: "【铁证搜集】利用【WASD】键穿梭在狭长肃杀的北京胡同，滑动鼠标旋转手电筒视界。为了安全，平坦的主干道上空无一物；所有25张历史相纸节点全部被精准散布在无法一眼看穿的【诱导路径（死胡同）】深处。你想将真相带回香港，就必须冒险踏入死胡同。当光芒中发现隐约浮现的黑白底片时，正对它按下【空格键】记录瞬间。",
      intro_3: "【快门自救】若耳机里传来急促、杂乱的空间军警脚步声，且四周血红边框狂闪，意味着你已被贴身拦截。你必须在 1.2 秒内果断按下【空格键】，利用相机的闪光灯致盲并瘫痪敌人 4 秒。此时，如果你规划的逃生路线正确或者运气足够好，便能在其瘫痪时迅速拉开距离逃脱。但这同样会消耗掉 1 张珍贵的底片。",
      intro_4: "注意：安全撤离前你必须至少成功拍下一张现场底片。如果 5 张底片全部完美记录了现场（未浪费于闪盲军警），你将解密暗房中最深处的绝密 28 张文献档案长卷。",
      choose_diff: "— 请选择潜入深度 / Select Difficulty —",
      easy: "容易 (25x25 街区 + 全局雷达地图)",
      normal: "普通 (35x35 街区 + 盲区罗盘指针)",
      hard: "死线 (45x45 巨型街区 + 重兵戒严合围)",
      custom: "自定义",
      custom_size: "街区迷宫大小 (25 - 100): ",
      custom_map: "允许启用高对比度全局小地图: ",
      btn_start: "破开铁幕潜入 / START",
      btn_resume: "封存相纸并继续前进 / CONTINUE",
      btn_retry: "重新装填底片 / RETRY",
      btn_menu: "返回主菜单 / MAIN MENU",
      film_remains: "🎞️ 剩余机身胶卷: ",
      audio_status: "空间音频引擎: ",
      exit_label: "【安全撤离点 / EXIT】",
      whisper_rec: "",
      victory_h2: "深红暗房 · 现场真相显影",
      victory_perfect: "【 绝密解锁：完整 28 张历史文献长卷 】",
      victory_p1: "反锁上房门，你将本次九死一生带回的胶卷浸入深红安全灯下的显影液中……",
      victory_perfect_p1: "机身溴化银药水完全渗透。你带出了最完整的初夏现场，尘封的历史文献长卷在这一刻全部复活。",
      reflection: "“历史的底片不仅涂抹在溴化银上，更镌刻在每个见证者的记忆深处。” 沉重的履带可以碾碎广场上的帐篷，高强度的强光可以烧毁底片，但那一年的呐喊，早已化作不灭的微光，在漫长而漆黑的岁月中，静静显影。",
      fail_title: "潜入宣告终止",
      fail_no_photo: "你虽然设法到达了撤离点，但相机内空无一物。没有铁证，全世界将遗忘今晚发生的一切。任务失败。"
    },
    whispers: [
      "“小伙子，手电筒收着点！前面街角有戒严部队的暗哨！”",
      "“把这些底片带去香港……求你们，让全世界看清楚这儿发生了什么……”",
      "“市民们正在西单用双层巴士筑起路障，快去那边拍下铁证！”",
      "“同学，喝口水吧。广播里说撤退，可我们身后就是退无可退的明天。”",
      "“听……那是木樨地方向传来的声音……他们真的开枪了……”",
      "“孩子，活下去。替我们这些没法离开的人，把真相告诉后代。”",
      "“记者先生，请拍一拍我们。如果明天我们不在了，这就是我们活过的证据。”"
    ],
    captions: {
      1: "那是充满抗争张力的街头镜头。北京市民如潮水般聚集在主干道上，白旗高扬，标语口号直指当时令人窒息的愚民政策，空气中凝结着压抑已久的反叛与觉醒力量。",
      2: "镜头记录下了北京工人阶级集体罢工的震撼历史瞬间。蓝领工人们高举着写有‘邓小平下台’的巨大横幅，标志着这场运动正式突破了学生群体的边界，走向全社会的联合。",
      3: "极度刺眼且残酷的纪实底片：头戴钢盔的武装警察无情地将沉重的棍棒挥向了手无寸铁的请愿市民，和平呼吁在这一刻被强行撕碎，蒙上了密不透风的血色阴影。",
      4: "从高处俯瞰，数万名来自各大高校的大学生在天安门广场前排成紧密的方阵，静坐绝食。他们用绝食请愿的方式，用年轻的身体对抗冷酷的权力，表达最后的抗争誓言。",
      5: "钢铁怪兽露出了獠牙。中共的装甲坦克在柏油路上碾出刺耳的轰鸣，毫无顾忌地全速冲向避让不及的抗议人群，历史的尊严在这一刻被重型履带无情碾压。",
      6: "这是一张让人窒息的近景底片：一名年轻的男大学生倒在血泊中，伤势惨重、血肉模糊。青春的面容在铁血的清场中被摧残得面目全非，记录了那一晚最真实的残酷。",
      7: "戒严部队的重型坦克长驱直入北京城市核心街区。滚滚的黑烟与未散的硝烟将曾经熟悉的街道吞噬，繁华的市景在强权介入下瞬间沦为了惨烈的战场废墟。",
      8: "抗议队伍中极具智慧与尊严的画面：百余辆自行车自发在前方排开筑起前锋防线，中间几位坚毅的抗议者驾驶着一辆农用拖拉机，手持红旗在围观市民的瞩目下决绝前行。",
      9: "惊呼与哭喊打破了黑夜。大批北京市民自发围成一圈，焦急而悲痛地注视着一位因伤势过重、生命垂危而被紧急送上临时担架的抗议者，生死悬于一线。",
      10: "快门定格了街头互助的生死时速：一名普通的北京市民疯狂地蹬着自行车，在混乱的街头和流弹的威胁下，拼尽全力帮助身负重伤的陌生抗议者撤离危险现场。",
      11: "万余名请愿抗议者静坐在人民英雄纪念碑前。人群中央，一位年轻学生穿着印有‘My Life is Ours My Love is Yours’的卫衣，在肃杀的铁幕下展现出无悔的纯真与赤诚。",
      12: "庄严的建筑前拉起了死亡的防线。大批戴着钢盔、手持盾牌的武警在人民大会堂和人民英雄纪念碑前黑压压地集结，冰冷的枪刺在胡同的夜色中闪烁着寒光。",
      13: "市民们不再坐以待毙。愤怒的民众爬上了失去行动能力的坦克，用最原始的工具和砖石将这台战争机器成功掀翻并彻底销毁在长安街头，彰显了反抗的意志。",
      14: "在天安门城楼毛泽东巨幅肖像的对立面，通宵达旦的学生们用石膏与泡沫塑料连夜竖起了一尊高耸洁白的自由女神像，形成了某种绝妙而充满张力的历史性对峙。",
      15: "清晨的微光穿透硝烟，抗议者们在帐篷林立的天安门广场上奋力拉开了一幅写有‘我有一个梦’的白底横幅，致敬着跨越时空的自由呐喊与尊严追求。",
      16: "游行队伍的最前列，大学生们神圣地抬着前主席胡耀邦的巨幅彩色肖像。人们用对这位清廉逝者的深切悼念，敲响了反腐败、要民主、要新闻自由的战鼓。",
      17: "充满青春反叛与抗争力量的画面：几名自由派青年全然不顾周遭的危险，攀坐在长安街上的大型路牌和交通灯铁杆顶端，居高临下地俯瞰着抗议的红色人海。",
      18: "名震全球的历史定格：在宽阔、空旷而肃杀的长安街中央，一个孤独瘦削的青年男子孤身挺身阻挡在四辆直线排列的庞大坦克前，用血肉之躯践行了不屈的尊严。",
      20: "在局势彻底恶化前，数十名高校学生代表和工人纠察队成员紧紧聚在人民大会堂斑驳的石柱前，齐刷刷地望向记者的镜头，眼神中满是清澈、坚定与无畏。",
      19: "万余名抗议市民与学生齐聚在天安门前。从高处鸟瞰，整座广场被围得水泄不通，那是无数普通人为了共同的明天，用血肉筑起的、不可动摇的民主长城。",
      21: "混乱的撤退现场，一名面部中弹、双目受创严重的年轻学生，将双手颤抖地搭在另外两位男抗议者的肩膀上，在同胞的含泪搀扶下艰难地摸索着撤离历史的血迹。",
      22: "闪光灯晃过了胡同的阴霾：一名额头上缠着白色绝食誓言带的高校学生，在密集的自行车抗议洪流旁，转头对着香港记者的镜头比出了一个坚定的‘V’字胜利手势。",
      23: "在主要的十字路口，成百上千的北京民众自发组成了密不透风的人墙，将中共派出的戒严坦克牢牢围困在街头，试图用痛切的劝说唤醒年轻士兵的良知。",
      24: "夜幕降临，抗议者们再度聚集在天安门广场上，高举着蜡烛与手电筒，紧紧簇拥在洁白的自由女神像四周，点点微光在黑夜中汇聚成了不灭的星海。",
      25: "学生代表们庄严地将胡耀邦的巨幅遗像贴在人民英雄纪念碑汉白玉基座正中，两侧高举着‘民主之光耀邦’的素色横幅，以此确立了这场运动追求清廉与自由的起点。",
      26: "在密集的枪鸣声后，市民们用自发的默契与大无畏的勇气，冒着流弹将一名中弹、身受重伤的年轻抗议者抬上临时单架，在狭窄的胡同中一路狂奔寻找医院。",
      27: "一名面容极为坚毅的学生代表背着厚重的木质牌匾，上面用毛笔一笔一划写满了他们的绝食誓言，向冰冷的权力表达了促进民主化进程和国家繁荣的决死决心。",
      28: "极具震撼力的兵民同心瞬间：几名选择违抗开枪命令的良知军人选择扔下武器，与围阻的群众站在一起，共同用身体阻止后续武装装甲车的前进。"
    }
  },
  zt: { // 繁體中文
    ui: {
      title: "1989 · 鐵幕鏡頭",
      subtitle: "The Lens of History",
      intro_1: "【歷史前夜】1989年6月，北京。長夜如墨，戒嚴的陰影籠罩街頭。作為一名孤身前往現場的香港紀實記者，你正站在歷史的十字路口。四周是絕對不透光的磚石圍牆，牆角後全是不見底的盲區，危險隨時可能從陰暗處暴起。你唯一的武器，是胸前掛著的一台老舊膠片相機，以及暗盒裡僅剩的 5 張膠卷。",
      intro_2: "【鐵證搜集】利用【WASD】鍵穿梭在狹長肅殺的北京胡同，滑動滑鼠旋轉手電筒視界。為了安全，平坦的主幹道上空無一物；所有25張歷史相紙節點全部被精準散佈在無法一眼看穿的【誘導路徑（死胡同）】深處。你想將真相帶回香港，就必須冒險踏入死胡同。當光芒中發現隱約浮現的黑白底片時，正對它按下【空格鍵】記錄瞬間。",
      intro_3: "【快門自救】若耳機裡傳來急促、雜亂空間軍警腳步聲，且四周血紅邊框狂閃，意味著你已被貼身攔截。你必須在 1.2 秒內果斷按下【空格鍵】，利用相機的閃光燈致盲並癱瘓敵人 4 秒。此時，如果你規劃的逃生路線正確或者運氣足夠好，便能在其癱瘓時迅速拉開距離逃脫。這同樣會消耗掉 1 張珍貴的底片。",
      intro_4: "注意：安全撤離前你必須至少成功拍下一張現場底片。如果 5 張底片全部完美記錄了現場（未浪費於閃盲軍警），你將解密暗房中最深處的絕密 28 張文獻檔案長卷。",
      choose_diff: "— 請選擇潛入深度 / Select Difficulty —",
      easy: "容易 (25x25 街區 + 全局雷達地圖)",
      normal: "普通 (35x35 街區 + 盲區羅盤指針)",
      hard: "死線 (45x45 巨型街區 + 重兵戒嚴合圍)",
      custom: "自定義",
      custom_size: "街區迷宮大小 (25 - 100): ",
      custom_map: "允許啟用高對比度全局小地圖: ",
      btn_start: "破開鐵幕潛入 / START",
      btn_resume: "封存相紙並繼續前進 / CONTINUE",
      btn_retry: "重新裝填底片 / RETRY",
      btn_menu: "返回主菜單 / MAIN MENU",
      film_remains: "🎞️ 剩餘機身膠卷: ",
      audio_status: "空間音訊引擎: ",
      exit_label: "【安全撤離點 / EXIT】",
      whisper_rec: "",
      victory_h2: "深紅暗房 · 現場真相顯影",
      victory_perfect: "【 絕密解鎖：完整 28 張歷史文獻長卷 】",
      victory_p1: "反鎖上房門，你將本次九死一生帶回的膠卷浸入深紅安全燈下的顯影液中……",
      victory_perfect_p1: "機身溴化銀藥水完全滲透。你帶出了最完整的初夏現場，塵封歷史文獻長卷在這一刻全部復活。",
      reflection: "“歷史的底片不僅塗抹在溴化銀上，更鐫刻在每個見證者的記憶深處。” 沉重的履帶可以碾碎廣場上的帳篷，高強度的強光可以燒毀底片，但那一年的吶喊，早已化作不滅的微光，在漫長而漆黑的歲月中，靜靜顯影。",
      fail_title: "潛入宣告終止",
      fail_no_photo: "你雖然設法到達了撤離點，但相機內空無一物。沒有鐵證，全世界將遺忘今晚發生的一切。任務失敗。"
    },
    whispers: [
      "“小夥子，手電筒收著點！前面街角有戒嚴部隊的暗哨！”",
      "“把這些底片帶去香港……求你們，讓全世界看清楚這兒發生了什麼……”",
      "“市民們正在西單用雙層巴士築起路障，快去那邊拍下鐵證！”",
      "“同學，喝口水吧。廣播裡說撤退，可我們身後就是退無可退的明天。”",
      "“聽……那是木樨地方向傳來的聲音……他們真的開槍了……”",
      "“孩子，活下去。替我們這些沒法離開的人，把真相告訴後代。”",
      "“記者先生，請拍一拍我們。如果明天我們不在了，這就是我們活過的證據。”"
    ],
    captions: {
      1: "鏡頭捕捉到了長安街頭湧動的市民浪潮，人們高舉著白旗，口號聲直指當時令人窒息的愚民體制，空氣中凝聚著壓抑已久的叛逆與覺醒力量。",
      2: "鏡頭記錄下了北京工人階級集體罷工的震撼歷史瞬間。藍領工人們高舉著寫有‘鄧小平下台’的巨大橫幅，標誌著這場運動正式突破了學生群體的邊界，走向全社會的聯合。",
      3: "極度刺眼且殘酷的紀實底片：頭戴鋼盔的武裝警察無情地將沉重的棍棒揮向了手無寸鐵的請願市民，和平呼吁在這一刻被強行撕碎，蒙上了密不透風的血色陰影。",
      4: "從高處俯瞰，數萬名來自各大高校的大學生在天安門廣場前排成緊密的方陣，靜坐絕食。他們用絕食請願的方式，用年輕的身體對抗冷酷的權力，表達最後的抗爭誓言。",
      5: "鋼鐵怪獸露出了獠牙。中共的裝甲坦克在柏油路上碾出刺耳的轟鳴，毫無顧忌地全速衝向避讓不及的抗議人群，歷史的尊嚴在這一刻被重型履帶無情碾壓。",
      6: "這是一張讓人窒息的近景底片：一名年輕的男大學生倒在血泊中，傷勢慘重、血肉模糊。青春的面容在鐵血的清場中被摧殘得面目全非，記錄了那一晚最真實的殘酷。",
      7: "戒嚴部隊的重型坦克長驅直入北京城市核心街區。滾滾的黑煙與未散的硝煙將曾經熟悉的街道吞噬，繁華的市景在強權介入下瞬間淪為了慘烈的戰場廢墟。",
      8: "抗議隊伍中極具智慧與尊嚴的畫面：百餘輛自行車自發在前方排開築起前鋒防線，中間幾位堅毅的抗議者駕駛著一輛農用拖拉機，手持紅旗在圍觀市民的矚目下決絕前行。",
      9: "驚呼與哭喊打破了黑夜。大批北京市民自發圍成一圈，焦急而悲痛地注視著一位因傷勢过重、生命垂危而被緊急送上臨時擔架的抗議者，生死懸於一線。",
      10: "快门定格了街頭溫情與悲壯的互助：一名普通的北京市民瘋狂地蹬著自行車，在混亂的街頭和流彈的威脅下，拼盡全力幫助身負重傷的陌生抗議者撤離危險現場。",
      11: "廣場上密集靜坐的溫和面孔。人群中央，一位年輕學生穿著印有‘My Life is Ours My Love is Yours’的衛衣，在肅殺的鐵幕下展現出無悔的真摯與赤誠。",
      12: "莊嚴的建築前拉起了死亡的防線。大批戴著鋼盔、手持盾牌的武警在人民大會堂和人民英雄紀念碑前黑壓壓地集結，冰冷的槍刺在胡同的夜色中閃爍著寒光。",
      13: "市民們不再坐以待斃。憤怒的民眾爬上了失去行動能力的坦克，用最原始的工具和磚石將這台戰爭機器成功掀翻並徹底銷毀在長安街頭，彰顯了反抗的意志。",
      14: "在天安門城樓毛澤東巨幅肖像的對立面，通宵達旦的學生們用石膏與泡沫塑料連夜樹立起了一尊高聳潔白的自由女神像，形成了某種絕妙而充滿張力的歷史性對峙。",
      15: "晨曦微露的廣場上，抗議者們用顫抖卻堅定的雙手，拉開了一幅寫有‘我有一個夢’的白底橫幅，致敬著跨越時空的自由吶喊與尊嚴追求。",
      16: "遊行隊伍的最前列，大學生們神聖地抬著前主席胡耀邦的巨幅彩色肖像。人們用對這位清廉逝者的深切悼念，敲響了反腐敗、要民主、要新聞自由的戰鼓。",
      17: "充滿青春叛逆與抗爭力量的畫面：幾位自由派青年不顧周遭的危險，攀坐在長安街上的大型路牌和交通燈鐵桿頂端，居高臨下地俯瞰著抗議的紅色人海。",
      18: "名震全球的歷史定格：在寬闊、空曠而肅殺的長安街中央，一個孤獨瘦削的青年男子孤身挺身阻擋在四輛直線排列的龐大坦克前，用血肉之軀踐行了不屈的尊严。",
      19: "廣場被密密麻麻的抗議人群填得水洩不通。從高處鳥瞰，那是無數普通人為了共同的明天，用血肉築起的、不可動搖的民主長城。",
      20: "在局勢徹底惡化前，數十名高校學生代表和工人糾察隊成員緊緊聚在人民大會堂斑駁的石柱前，齊刷刷地望向記者的鏡頭，眼神中滿是清澈、堅定與無畏。",
      21: "混亂的撤退現場，一名面部中彈、雙目受創嚴重的年輕學生，將雙手顫抖地搭在另外兩位男抗議者的肩膀上，在同胞的含淚攙扶下艱難地摸索著撤離歷史的血跡。",
      22: "閃光燈晃過了小巷的陰霾：一名額頭上纏著白色絕食誓言帶的高校學生，在密集自行車抗議洪流旁，轉頭對著香港記者的鏡頭比出了一個堅定的『V』字勝利手勢。",
      23: "長安街交匯處，北京民眾自發形成了密不透風的人牆，用血肉之軀將中共派出的重型坦克團團圍困，試圖用痛切的勸說喚醒年輕士兵的良知。",
      24: "夜幕降臨，抗議者們再度聚集在天安門廣場上，高舉著蠟燭與手電筒，緊緊簇擁在潔白的自由女神像四周，點點微光在黑夜中匯聚成了不滅的星海。",
      25: "學生代表們莊嚴地將胡耀邦的巨幅遺像貼在人民英雄紀念碑漢白玉基座正中，兩側高舉著‘民主之光耀邦’的素色橫幅，以此確立了這場運動追求清廉與自由的起點。",
      26: "在密集的槍鳴聲後，市民們用自發的默契與大無畏的勇氣，冒著流彈將一名中彈、身受重傷的年輕抗議者抬上臨時單架，在狹窄的胡同中一路狂奔尋找醫院。",
      27: "一名面容極為堅毅的學生代表背著厚重的木質牌匾，上面用毛筆一筆一劃寫滿了他們的絕食誓言，向冰冷的權力表達了不惜以生命促進國家民主化進程的決死決心。",
      28: "極具震撼力的兵民同心瞬間：幾名選擇違抗開槍命令的良知軍人選擇扔下武器，與圍阻的群眾站在一起，共同用身體阻止後續武裝裝甲車的前進。"
    }
  },
  en: { // 英文模式 (UI 及 Captions 完全匹配)
    ui: {
      title: "1989 · The Iron Curtain Lens",
      subtitle: "The Lens of History",
      intro_1: "[The Eve of History] June 1989, Beijing. The night is pitch black, and the shadow of martial law covers the city. As a lone photojournalist from Hong Kong, you stand at the ultimate crossroads of history. Brick walls completely block your line of sight. Blind zones hide behind every corner, and danger can strike at any moment. Your only weapon is an old analogue camera with only 5 frames of film remaining.",
      intro_2: "[Evidence Gathering] Traverse the narrow, grim Beijing alleys using [WASD], and move your mouse to aim the flashlight. To ensure balance, the open main roads are completely clear; all 25 critical photo nodes are hidden deep within 'Decoy Paths' (dead ends). If you want to bring the truth out, you must take risks. When a silver bromide sheet appears in the beam, face it directly and press [SPACE] to capture.",
      intro_3: "[Shutter Defense] If you hear rushing spatial footsteps and the screen flashes crimson, an enemy is upon you. You must press [SPACE] within 1.2 seconds to blind and stun them for 4 seconds. If your route is correct or if you have enough luck, you can slip away into a safe corner. Note that this action also consumes 1 frame of valuable film.",
      intro_4: "Requirement: You must secure at least 1 historical photo to escape. If you complete the mission with 5 perfect records without wasting film on blinding troops, the complete 28-image roll will be decrypted.",
      choose_diff: "— Choose Infiltration Depth / Custom Settings —",
      easy: "Easy (25x25 Grid + Full HUD Radar Minimap)",
      normal: "Normal (35x35 Grid + Blind Zone Compass Needle)",
      hard: "Martial Law (45x45 Huge Grid + Aggressive 合围 AI)",
      custom: "Custom Mode",
      custom_size: "Maze Street Size (25 - 100): ",
      custom_map: "Enable Full Radar Surveillance Minimap: ",
      btn_start: "PENETRATE THE CURTAIN / START",
      btn_resume: "SECURE NEGATIVE & CONTINUE",
      btn_retry: "RELOAD FILM / RETRY",
      btn_menu: "MAIN MENU",
      film_remains: "🎞️ Analogue Film Left: ",
      audio_status: "Web Audio Synthesizer: ",
      exit_label: "【SAFE EXIT ZONE / EXIT】",
      whisper_rec: "",
      victory_h2: "Darkroom · Chemical Image Developing",
      victory_perfect: "【 CHRONICLE UNLOCKED: THE FULL 28-IMAGE LITERATURE ROLL 】",
      victory_p1: "Locking the door, you submerge the precious film sheets into the developer fluid under the deep red safety light...",
      victory_perfect_p1: "The chemical dissolves completely. You successfully smuggled out the entire memory of early summer. Every single archive is now resurrected.",
      reflection: "'The negatives of history are not merely coated on silver bromide; they are engraved into the memory of every witness.' Heavy treads can crush the tents, intense light can burn the film, but the cries of that summer have turned into an eternal glimmer, silently developing through the dark ages.",
      fail_title: "Infiltration Terminated",
      fail_no_photo: "You reached the exit grid, but your camera darkbox is completely empty. Without evidence, the world will forget tonight. Mission Failed."
    },
    whispers: [
      "\"Keep your flashlight down, kid! Martial law sentries are guarding the next street corner!\"",
      "\"Bring these negatives back to Hong Kong... Please, let the world see what truly happened here...\"",
      "\"Citizens are building barricades with double-decker buses at Xidan! Go there and take photos!\"",
      "\"Have some water, student. The radio says retreat, but behind us is a tomorrow with no escape.\"",
      "\"Listen... those sounds are coming from Muxidi... They are actually firing live rounds...\"",
      "\"Live on, child. Tell our descendants the absolute truth on behalf of those who cannot leave.\"",
      "\"Journalist, please take a photo of us. If we are not here tomorrow, this is the proof that we lived.\""
    ],
    captions: {
      1: "The lens captures a massive surge of citizens on Chang'an Avenue raising white flags, courageously protesting against systemic obscurantism as an energy of long-suppressed awakening fills the air.",
      2: "Beijing workers join in a massive, historic solidarity strike. Heavy banners flutter in the wind, demanding top leadership to step down, marking the expansion of the movement to all social classes.",
      3: "A brutal, eye-piercing piece of documentation: fully equipped martial forces relentlessly swing heavy batons at unarmed citizens, painting a peaceful petition in deep crimson blood.",
      4: "Tens of thousands of college students sit tightly organized in front of Tiananmen Square, entering a tragic hunger strike, offering their young bodies to demand basic constitutional dignity.",
      5: "Heavy armored tank units screech on the asphalt, charging directly into fleeing crowds without hesitation, ruthlessly crushing the path of historical justice under massive iron treads.",
      6: "A tragic, devastating close-up narrative: a young male student lies in a pool of blood, his heavily mutilated face showing the absolute cost of the regime's iron fist crackdown.",
      7: "Columns of battle tanks break through urban blocks, leaving a trail of thick fire and smoke that completely transforms familiar city avenues into a grim warzone ruin.",
      8: "An image filled with wisdom and courage: hundreds of citizens on bicycles form a protective vanguard shield, escorting protestors on an agricultural tractor holding a red flag.",
      9: "Amid desperate cries, citizens gather swiftly in a circle to lift a critically wounded protestor onto an emergency stretcher, fighting the clock for survival.",
      10: "A snapshot of pure bravery: a citizen pedals furiously on a bicycle through stray bullets and flames, carrying a wounded compatriot out of the danger zone.",
      11: "A calm collective protest before the square monument. At the center, a student wears a sweatshirt printed with 'My Life is Ours My Love is Yours,' capturing absolute sincerity under the iron curtain.",
      12: "A dark line of blockade forms as martial forces and armed police gather heavily before the Great Hall of the People, bayonets gleaming coldly in the dark alleys.",
      13: "Refusing to wait for fate, an angry crowd climbs onto a disabled heavy tank, using basic tools and raw courage to completely destroy it on the street.",
      14: "Directly opposite the massive portrait of Mao Zedong, students work overnight to erect a plaster Statue of Goddess of Democracy, creating a profound historical confrontation.",
      15: "As dawn breaks over the square, protestors raise a banner reading 'I Have a Dream,' bridging time and space with an eternal call for freedom and human rights.",
      16: "Students march with a giant colored portrait of the late Hu Yaobang, using the memory of an incorruptible leader to strike against systemic corruption.",
      17: "An image filled with youthful rebellion: liberal youths climb and sit atop Chang'an Avenue road signs and traffic lights, overlooking the ocean of protestors.",
      18: "The legendary stand of history: a lone, slender figure stands defiantly in the middle of Chang'an Avenue, stopping a column of four massive battle tanks.",
      20: "Before the final crackdown, student representatives and labor leaders stand by the pillars of the Great Hall, facing the lens with clear and unyielding eyes.",
      19: "The square is packed to absolute capacity. Viewed from above, it is an unbreakable fortress of flesh and blood built by ordinary people for a shared destiny.",
      21: "A chaotic retreat scene where a blinded, heavily bleeding student rests his hands on the shoulders of two companions, navigating the narrow alleys with shared strength.",
      22: "A flash of hope in the grim alleyway: a student wearing a white hunger-strike headband flashes a resolute 'V' victory sign right into the reporter's lens.",
      23: "At a major intersection, citizens form a human wall around armored tanks, attempting to appeal to the conscience of the soldiers inside.",
      24: "Under the night sky, thousands of protestors holding candles surround the white Goddess of Democracy, weaving a galaxy of starlight in the dark.",
      25: "Student representatives place Hu Yaobang's giant portrait onto the Monument base, holding banners reading 'The Light of Democracy' to mark the movement's start.",
      26: "Following heavy gunfire, citizens brave the stray bullets to carry a severely shot protestor through narrow hutong alleys, searching for an open hospital.",
      27: "A student carries a heavy wooden tablet inscribed with their hunger strike oath, declaring an absolute devotion to the democratic progress of their nation.",
      28: "A breathtaking moment of shared humanity: soldiers defying the order to shoot throw down their weapons and join the crowd to stop subsequent armored vehicles."
    }
  },
  ja: { // 日文模式
    ui: {
      title: "1989 · 鉄幕のレンズ",
      subtitle: "The Lens of History",
      intro_1: "【歴史の前夜】1989年6月、北京。夜は漆黒に包まれ、戒厳令の影が街を覆う。香港から単身で潜入した記録記者として、あなたは歴史の分岐点に立っている。光を一切通さないレンガの壁が視界を遮り、死角からはいつ敵が襲ってくるか分からない。あなたの唯一の武器は、5枚のフィルムが残された古いカメラだけだ。",
      intro_2: "【証拠の収集】[WASD]キーで静かに街を進み、マウスで手電筒を操作する。歴史の真実を捉えた印画紙は、すべて行き止まりの「誘導路（路地裏）」の奥深くに散らばっている。安全のため、大通りには何も配置されていない。真実を持ち帰るには、危険を冒して路地裏に入り、白く浮かび上がる相紙を見つけたら[SPACE]キーでシャッターを切る必要がある。",
      intro_3: "【シャッター防衛】もしイヤホンから軍警の足音が近づき、画面の縁が赤く点滅したら、敵に完全に包囲されている。1.2秒以内に[SPACE]キーを押し、強力なフラッシュで敵を4秒間目眩まし（スタン）させなければならない。敵が動けない間に正しいルートを選択すれば逃げ切ることができるが、貴重なフィルムを1枚消費する。",
      intro_4: "注意：脱出するには最低1枚の写真を撮影する必要がある。もしフィルムを自衛のために消費せず、5枚すべてを現場の記録に使用してクリアできれば、暗房の奥深くに隠された28枚の完全な歴史アーカイブが解禁される。",
      choose_diff: "— 潜入深度を選択してください / Custom Settings —",
      easy: "簡単 (25x25 マップ + 全局レーダーミニマップ)",
      normal: "普通 (35x35 マップ + 羅針盤ポインタ)",
      hard: "戒厳令 (45x45 巨大マップ + 包囲網強化)",
      custom: "カスタムモード",
      custom_size: "マップサイズ (25 - 100): ",
      custom_map: "ミニマップを表示する: ",
      btn_start: "鉄のカーテンを突き破る / START",
      btn_resume: "フィルムを格納して進む / CONTINUE",
      btn_retry: "フィルムを再装填 / RETRY",
      btn_menu: "メインメニュー / MAIN MENU",
      film_remains: "🎞️ 残りフィルム: ",
      audio_status: "オーディオ接続: ",
      exit_label: "【安全脱出地点 / EXIT】",
      whisper_rec: "",
      victory_h2: "真紅の暗室 · 現像の刻",
      victory_perfect: "【 機密解除：完全なる28枚の歴史絵巻 】",
      victory_p1: "ドアを施錠し、あなたは命がけで持ち帰ったフィルムを、赤い安全灯の下で現像液に浸した……",
      victory_perfect_p1: "臭化銀が完全に溶け出し、あなたが記録した真実が、28枚の完全な歴史アーカイブとしてここに蘇る。",
      reflection: "「歴史のネガは臭化銀に塗られるだけでなく、目撃者全員の記憶の奥深くに刻まれている。」 重い戦車がテントを押し潰し、強烈な光がフィルムを焼き尽くそうとも、あの初夏の叫びは消えない微光となり、暗い歳月の中で静かに現像され続けている。",
      fail_title: "潜入作戦終了",
      fail_no_photo: "脱出地点に到達したものの、カメラの中は空っぽだった。鉄証がなければ、世界は今夜的出来事を忘れてしまうだろう。ミッション失敗。"
    },
    whispers: [
      "「ライトを消せ、若者よ！次の角に戒厳部隊の暗哨がいる！」",
      "「このネガを香港に届けてくれ…世界に真実を伝えてほしい…」",
      "「市民が西単でバスを使ってバリケードを築いている！急げ！」",
      "「学生さん、水を飲みなさい。ラジオは退却を告げているが、私たちの後ろに退路はない。」",
      "「聞け…木樨地の方から音がする…彼らは本当に実弾を撃っている…」",
      "「生きてくれ、我が子よ。去れない私たちの代わりに、真実を後世に伝えてくれ。」",
      "「記者さん、私たちの写真を撮ってください。明日私たちが消えても、これが生きた証拠だ。」"
    ],
    captions: {
      1: "長安街に押し寄せる市民の波をレンズが捉えた。白旗を掲げ、当時の愚民政策を痛烈に批判する人々の声が、覚醒の力として響き渡っている。",
      2: "北京の労働者階級による一斉ストライキの衝撃的な瞬間。「トウ小平退陣」を求める巨大な横幅が風に揺れ、運動が社会全体に広がったことを示している。",
      3: "極めて生々しい記録：完全武装した戒厳部隊が、武器を持たない市民に容赦なく警棒を振り下ろし、平和的な請願が血に染まった瞬間。",
      4: "天安門広場を埋め尽くすハンガーストライキの学生たち。数万人の若者がハンガーストライキを行い、命を賭して権力に尊厳を求めた。",
      5: "アスファルトを削る戦車の轟音が響き、戒厳部隊の重戦車が逃げ惑う群衆に向かって突入する。歴史の軌跡が冷酷に踏みにじられた。",
      6: "直視できないほどの悲劇的なネガ：血の海の中に倒れた若い男子大学生。その無残な姿は、鉄の爪がもたらした残酷な現実を物語っている。",
      7: "北京の市街地を突き破る戦車部隊。立ち上る黒煙と硝烟が、かつて見慣れた街並みを凄惨な戦場へと変えてしまった。",
      8: "連帯の意志を示す象徴的な光景：数百台の自転車が自発的に先導の盾となり、赤旗を掲げた農業用トラクターを護衛しながら進む。",
      9: "悲痛な叫びが響く中、市民たちが素早く集まり、重傷を負って生死の境をさまよう抗議者を即席の担架に乗せて搬送する。",
      10: "極限の勇気の瞬間：流弾と炎が飛び交う中、一人の北京市民が自転車を猛烈に漕ぎ、負傷した同胞を危険地帯から救出する。",
      11: "広場に密集する穏やかな抗議者たち。中心には「My Life is Ours My Love is Yours」と印刷されたパーカーを着た学生がおり、純粋な愛が描かれている。",
      12: "人民大会堂と記念碑の前に、不気味な包囲網が形成される。武装警察が黒々と集結し、銃剣が暗闇の中で冷たく光っている。",
      13: "市民たちはただ待つことを拒み、動けなくなった重戦車に飛び乗り、怒りと原始的な道具を使って街頭で完全に破壊した。",
      14: "毛沢東の巨大な肖像画の真向かいに、学生たちが徹夜で発泡スチロールと石膏を使って白い「民主の女神像」を建て、歴史的な対峙が生まれた。",
      15: "朝霧が立ち込める広場で、抗議者たちが震える手で「私には夢がある」と書かれた横断幕を掲げ、自由への不滅の叫びを響かせる。",
      16: "学生たちが故・胡耀邦主席の巨大な肖像画を掲げて行進する。清廉な故人への思慕が、腐敗打倒と民主化を求める戦いの呼び水となった。",
      17: "若者の反逆と抗争のエネルギーに満ちたカット：数人の青年が危険を顧みず長安街の道路標識や信号機の上に登り、抗議の海を見下ろしている。",
      18: "世界中を震撼させた歴史の定点：広大で静まり返った長安街の中央で、一人の痩せた男が4台の戦車の前に立ち塞がり、鉄の怪物に生身で挑む。",
      20: "事態が破滅に向かう直前、数十人の学生代表と労働者リーダーが人民大会堂の石柱に寄り添い、澄んだ毅然とした瞳でレンズを見つめている。",
      19: "広場は完全に抗議者で埋め尽くされた。上空から見下ろすと、共通の運命のために一般市民が築き上げた、揺るぎない血肉の城壁であった。",
      21: "混乱する撤退のさなか、頭部を負傷し失明の危機にある学生が、2人の仲間の肩に手を預け、支えられながら一歩一歩進む。",
      22: "暗い路地に差し込んだ希望の光：頭に白いハンガーストライキの帯を巻いた学生が、自転車の波の横で、記者のレンズに向かって力強くVサインを作る。",
      23: "長安街の交差点で、北京の群衆が人間の壁を作り、派遣された重戦車を完全に包囲。兵士たちの良心に必死に訴えかけている。",
      24: "夜の天安門広場。ろうそくを手にした数千人の抗議者が白い「民主の女神像」を囲み、微かな光が集まって暗闇の中に星空を描き出した。",
      25: "学生代表が胡耀邦の巨大な肖像画を英雄記念碑の台座に厳かに貼り付け、「民主の光」と書かれた横断幕を掲げて運動の原点を築いた。",
      26: "激しい銃声の後、市民たちは流弾を恐れず、銃撃された重傷者を担架で胡同（路地裏）を駆け抜け、必死に病院を探す。",
      27: "引き締まった表情の学生が、墨でハンガーストライキの誓いが書かれた重い木製の板を背負い、命を賭して民主化を推し進める決意を示す。",
      28: "兵士と市民が心を一つにした衝撃の瞬間：発砲命令を拒否した数人の兵士が武器を捨て、群衆と共に装甲車の前進を自らの体で阻止した。"
    }
  }
};